name: "PySHiELD translate tests"

# Run these these whenever ...
on:
  workflow_call: # ... called from a downstream repo
    inputs:
      component_trigger:
        type: boolean
        default: false
        required: false
      component_name:
        type: string
        default: ''
        required: false
  pull_request: # ... a PR is opened / updated
  merge_group: # ... the PR is added to the merge queue
  push:
    branches:
      - main # ... when merging into the main branch

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pyshield_translate_tests:
    runs-on: ubuntu-latest
    steps:
      - name: External trigger Checkout pySHiELD
        if: ${{inputs.component_trigger}}
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          repository: NOAA-GFDL/PySHiELD
          path: pySHiELD
          ref: develop

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11.13
          conda-remove-defaults: true
          auto-activate-base: false
          activate-environment: pyshield_test_env

      - name: Install mpi (MPICH flavor)
        shell: bash -l {0}
        run: pip install mpich

      - name: External trigger remove existing component in pySHiELD/develop
        shell: bash -l {0}
        if: ${{ inputs.component_trigger }}
        run: rm -rf ${GITHUB_WORKSPACE}/pySHiELD/${{inputs.component_name}}

      - name: Checkout hash that triggered CI
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          path: pySHiELD/${{inputs.component_name}}

      - name: external trigger Install packages for FV3 component
        shell: bash -l {0}
        if: ${{contains(inputs.component_name, 'FV3')}}
        run: |
          cd ${GITHUB_WORKSPACE}/pySHiELD
          pip3 install --upgrade pip setuptools wheel
          cd ${{inputs.component_name}} && pip3 install .[test] && cd ..
          pip3 install .[ndsl,test]
          pip install numpy==1.26.4
          conda remove sqlite

      - name: external trigger Install packages for NDSL component
        shell: bash -l {0}
        if: ${{contains(inputs.component_name, 'NDSL')}}
        run: |
          cd ${GITHUB_WORKSPACE}/pySHiELD
          pip3 install --upgrade pip setuptools wheel
          cd ${{inputs.component_name}} && pip3 install .[test] && cd ..
          pip3 install .[pyfv3,test]
          pip install numpy==1.26.4
          conda remove sqlite

      - name: Install pySHiELD packages
        shell: bash -l {0}
        if: ${{ !inputs.component_trigger}}
        run: |
          cd ${GITHUB_WORKSPACE}/pySHiELD
          pip install --upgrade pip setuptools wheel
          pip install .[ndsl,pyfv3,test]
          pip install numpy==1.26.4
          conda remove sqlite

      - name: Download data
        shell: bash -l {0}
        run: |
          cd ${GITHUB_WORKSPACE}/pySHiELD
          mkdir -p test_data
          cd test_data
          wget https://portal.nccs.nasa.gov/datashare/astg/smt/pace-regression-data/8.1.3_c12_6ranks_baroclinic.physics.tar.gz
          tar -xzvf 8.1.3_c12_6ranks_baroclinic.physics.tar.gz

      - name: Numpy Translate Test
        shell: bash -l {0}
        run: |
          cd ${GITHUB_WORKSPACE}/pySHiELD
          pytest \
            -v -s --data_path=./test_data/8.1.3/c12_6ranks_baroclinic/physics \
            --backend=numpy \
            --threshold_overrides_file=./tests/savepoint/translate/overrides/standard.yaml \
            ./tests/savepoint

      - name: Orchestrated dace:cpu Translate Test
        shell: bash -l {0}
        run: |
          cd ${GITHUB_WORKSPACE}/pySHiELD
          export FV3_DACEMODE=BuildAndRun
          export PACE_FLOAT_PRECISION=64
          export OMP_NUM_THREADS=10
          export PACE_LOGLEVEL=Debug
          pytest \
            -vvv -x -s --data_path=./test_data/8.1.3/c12_6ranks_baroclinic/physics \
            --backend=dace:cpu \
            --threshold_overrides_file=./tests/savepoint/translate/overrides/standard.yaml \
            ./tests/savepoint
